# Generated by Django 5.0.4 on 2024-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIN', models.CharField(db_index=True, max_length=14)),
                ('Tax_Year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Stat1', models.IntegerField(blank=True, null=True)),
                ('Stat2', models.IntegerField(blank=True, null=True)),
                ('Tri_Loc', models.TextField(blank=True, null=True)),
                ('Exe_Type', models.TextField(blank=True, null=True)),
                ('HO_Ex_EAV', models.IntegerField(blank=True, null=True)),
                ('HS_Ex_EAV', models.IntegerField(blank=True, null=True)),
                ('SF_Ex_EAV', models.IntegerField(blank=True, null=True)),
                ('LT_Ex_EAV', models.IntegerField(blank=True, null=True)),
                ('DisPer_EAV', models.IntegerField(blank=True, null=True)),
                ('RetVet_EAV', models.IntegerField(blank=True, null=True)),
                ('DisVet_EAV', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exemption',
                'unique_together': {('PIN', 'Tax_Year')},
            },
        ),
    ]
